### ISSUE TITLE
Unsure how to match figma values into this shape to get the same UI

### ISSUE THREAD

**Issue by StylianosGakis** [c5inco/smoother#1]
So looking at an example:
I got a shape in figma, which has a height of 64, a width of 300 and a corner radius of 12
Here is it with 0% smoothness, and 100% smoothness respectively.
| 0% | 100% |
| --- | --- |
| <img width="354" alt="image" src="https://github.com/c5inco/smoother/assets/44558292/57cb3963-8809-4112-803d-02ef3f0eb555"> | <img width="354" alt="image" src="https://github.com/c5inco/smoother/assets/44558292/f0ee7750-902f-4c91-9c5e-95f240a37167"> |

Then, using the debug app you got here, I plug dp as 12 and smoothness respectively, and I get this result
| 0% | 100% |
| --- | --- |
| <img width="566" alt="image" src="https://github.com/c5inco/smoother/assets/44558292/5f9e804c-5716-4c4c-94f3-bf10c6151782"> | <img width="566" alt="image" src="https://github.com/c5inco/smoother/assets/44558292/24ac68f3-f077-4e11-b212-96f2684fd8a0"> |

Now I am not sure if my eyes are deceiving me, but these two results look quite different right? The smoothness effect seems to only kick in when the corner radius is much bigger. I suspect there's an issue here with my conversions. Perhaps corner radius of 12 in Figma shouldn't necessarily be 12.dp in code? Any pointers here would be super appreciated!

**Comment by c5inco** [comment]
So one thing to always do is make sure the width and height match, since the smoothness effect can perceptually change based on the size of the shape.

Figma example:
<img width="723" alt="image" src="https://github.com/c5inco/smoother/assets/1253402/4aeca209-d337-49b7-a8da-9ab3ed1a50fc">

However, I believe something is incorrect on my end with the algorithm and/or Figma's algorithm has changed. I'll look into it, but I might also suggest looking at the new [shapes library from androidx](https://developer.android.com/jetpack/androidx/releases/graphics#graphics-shapes-1.0.0-alpha03) which should be a successor to this.

**Comment by StylianosGakis** [comment]
Mmm that's very interesting, I had never thought that the result changes so much depending on the content size. At least not until it was so close that it started converging towards going into a CircleShape basically.
I've also noticed that this library exists, but I had figured out that getting the specific Figma calculation of how they do corner shapes wouldn't be that straightforward, would it?
If you have already played around with making this shape happen with that library I would be super happy to see what you've tried so far. Otherwise I can try and spike it out a bit, see what that library has to offer to me. With the fear that I would probably need to know much more about geometry than I currently do 😅

**Comment by StylianosGakis** [comment]
Hey gave that library a try, if I am doing this correctly, this did feel quite easy to get working.

Got a RoundedPolygon like this
```
private fun RoundedPolygon.Companion.squircle(
  width: Float,
  height: Float,
  cornerRadius: Float,
  smoothing: Float,
): RoundedPolygon {
  require(width >= 0f)
  require(height >= 0f)
  return RoundedPolygon(
    vertices = listOf(
      PointF(0f, 0f),
      PointF(width, 0f),
      PointF(width, height),
      PointF(0f, height),
    ),
    rounding = CornerRounding(cornerRadius, smoothing),
  )
}
```
Where I can take it and plug it into a `androidx.compose.ui.graphics.Shape` like this
```
val squircleShape: Shape = object : Shape {
  override fun createOutline(size: Size, layoutDirection: LayoutDirection, density: Density): Outline {
    val squircle = RoundedPolygon.squircle(
      width = size.width,
      height = size.height,
      cornerRadius = with(density) { cornerRadius.dp.toPx() },
      smoothing = smoothing,
    )
    return Outline.Generic(squircle.toPath().asComposePath())
  }
}
```
Where `cornerRadius` and `smoothing` are floats here.


All together, for a snippet like this
```
@Composable
fun Shape() {
  Box(Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
    Column {
      var cornerRadius by remember { mutableFloatStateOf(12f) }
      var smoothing by remember { mutableFloatStateOf(1f) }
      val squircleShape: Shape = object : Shape {
        override fun createOutline(size: Size, layoutDirection: LayoutDirection, density: Density): Outline {
          val squircle = RoundedPolygon.squircle(
            width = size.width,
            height = size.height,
            cornerRadius = with(density) { cornerRadius.dp.toPx() },
            smoothing = smoothing,
          )
          return Outline.Generic(squircle.toPath().asComposePath())
        }
      }
      Box(
        modifier = Modifier
          .graphicsLayer(shape = squircleShape)
          .zoomable(rememberZoomState(20f)) // https://github.com/usuiat/Zoomable
          .height(64.dp)
          .fillMaxWidth()
          .align(Alignment.CenterHorizontally)
          .padding(horizontal = 16.dp)
          .background(Color(0xFFFBEDC5), squircleShape)
          .border(Dp.Hairline, Color(0xFFFFBF00), squircleShape),
      ) {
        Text(
          text = "A short message about something that needs attention, an error, info or...",
          fontSize = 14.sp,
          modifier = Modifier.padding(16.dp),
        )
      }
      Slider(cornerRadius, { cornerRadius = it }, valueRange = 0f..50f, modifier = Modifier.padding(horizontal = 16.dp))
      Text("corner radius:${cornerRadius.dp}")
      Slider(smoothing, { smoothing = it }, valueRange = 0f..1f, modifier = Modifier.padding(horizontal = 16.dp))
      Text("smoothing:$smoothing")
    }
  }
}
```

I see the result here:
![image](https://github.com/c5inco/smoother/assets/44558292/f855c704-082b-4dee-96c9-e5bd88f56f22)

And the same setup, with zoom on the card:
![image](https://github.com/c5inco/smoother/assets/44558292/571c119a-191e-4541-a1e1-1ab42dffb1f5)

Again I for real can't tell if this is 100% what Figma wants, but at least it looks like I should be doing the right thing 😅 And in the zoomed state you can tell that the border for example gets some odd-looking artifacts, but I guess this may be due to how the shape is very intricate and it's hard to draw? I am really not sure if I can do something better there. In contrast, if I use RoundedCornerShape() or just CircleShape, the border, again with Dp.Hairline width looks very crisp, none of these pixelated results.

Maybe I should move this discussion somewhere else though, I wonder where 🤔

**Comment by StylianosGakis** [comment]
Thanks again for suggesting that library, it seems to work perfectly fine. The border issue is just a generic issue with borders + adding arbitrary paths to them which is hard to render while also staying inside the bounds of the composable. Replacing it with something like this
```
.drawWithCache {
  val stroke = Stroke(1.dp.toPx())
  val path = (squircleShape.createOutline(size.copy(size.width, size.height), layoutDirection, this) as Outline.Generic).path
  onDrawWithContent {
    drawContent()
    drawPath(path, Color(0xFFFFBF00), style = stroke)
  }
}
```
Works wonders.

Gonna close this for now, but in general maybe you'd want to keep a note in the readme that this should now be possible with that library? Not sure what your goals are with this repository so I'm not gonna make any assumptions here, gonna close and if you want any help with adding the code snippet in the readme on how to make the shape, just like we did [here](https://github.com/HedvigInsurance/android/pull/1755) I'd be very happy to contribute it back here.

**Comment by c5inco** [comment]
Awesome very cool and exactly what I was hoping to see! Yeah I'll include a note in the README that is sample is obsolete and folks should use the shapes library instead.

I may update the same code here to show the comparison as well.
